/* Ported verbatim from the design file (Kura Portfolio.dc.html, lines 422-515).
   Do not reformat the GLSL — the strings are the contract. */

export const CLOUD_FRAG = [
  "precision highp float;",
  "uniform float uTime; uniform vec2 uRes; uniform vec2 uMouse; uniform float uDark;",
  "float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }",
  "float noise(vec2 p){",
  "  vec2 i = floor(p), f = fract(p);",
  "  vec2 u = f * f * (3.0 - 2.0 * f);",
  "  return mix(mix(hash(i), hash(i + vec2(1.0,0.0)), u.x), mix(hash(i + vec2(0.0,1.0)), hash(i + vec2(1.0,1.0)), u.x), u.y);",
  "}",
  "float fbm(vec2 p){ float v = 0.0, a = 0.5; for (int i = 0; i < 3; i++) { v += a * noise(p); p *= 2.03; a *= 0.5; } return v; }",
  "void main(){",
  "  vec2 uv = gl_FragCoord.xy / uRes.xy;",
  "  vec2 p = (uv - 0.5) * vec2(uRes.x / uRes.y, 1.0);",
  "  float t = uTime * 0.055;",
  "  vec2 q = p * 1.5 + vec2(t, -t * 0.7) + uMouse * 0.18;",
  "  float f = fbm(q + fbm(q * 1.7 + t) * 0.9);",
  "  float g = fbm(q * 0.7 - t * 1.3 + 4.0);",
  "  vec3 deep   = mix(vec3(0.086, 0.035, 0.647), vec3(0.020, 0.016, 0.043), uDark);",
  "  vec3 base   = mix(vec3(0.165, 0.078, 0.910), vec3(0.051, 0.043, 0.106), uDark);",
  "  vec3 violet = mix(vec3(0.404, 0.235, 0.976), vec3(0.125, 0.094, 0.239), uDark);",
  "  vec3 lilac  = mix(vec3(0.588, 0.400, 1.000), vec3(0.204, 0.165, 0.353), uDark);",
  "  vec3 col = mix(deep, base, smoothstep(0.15, 0.85, f));",
  "  col = mix(col, violet, smoothstep(0.45, 0.95, f * 1.15));",
  "  col = mix(col, lilac, smoothstep(0.62, 1.0, g) * 0.55);",
  "  float glow = smoothstep(0.95, 0.15, length(p * vec2(0.72, 1.25)));",
  "  col += violet * glow * 0.22;",
  "  float vig = smoothstep(1.35, 0.25, length(p));",
  "  col *= mix(0.72, 1.06, vig);",
  "  float dith = (hash(gl_FragCoord.xy + fract(uTime)) - 0.5) * 0.02;",
  "  gl_FragColor = vec4(col + dith, 1.0);",
  "}",
].join("\n");

export const LOGO_VERT = [
  "varying vec3 vN; varying vec3 vP; varying float vD;",
  "void main(){",
  "  vN = normalize(normalMatrix * normal);",
  "  vec4 mv = modelViewMatrix * vec4(position, 1.0);",
  "  vP = mv.xyz;",
  "  vD = position.z * 0.02;",
  "  gl_Position = projectionMatrix * mv;",
  "}",
].join("\n");

export const LOGO_FRAG = [
  "precision highp float;",
  "uniform float uTime;",
  "varying vec3 vN; varying vec3 vP; varying float vD;",
  "void main(){",
  "  vec3 n = normalize(vN);",
  "  vec3 v = normalize(-vP);",
  "  float fres = pow(1.0 - clamp(dot(n, v), 0.0, 1.0), 2.2);",
  "  vec3 core = vec3(0.20, 0.09, 0.85);",
  "  vec3 mid  = vec3(0.55, 0.42, 1.00);",
  "  vec3 hot  = vec3(0.92, 0.86, 0.68);",
  "  vec3 ice  = vec3(0.72, 0.90, 1.00);",
  "  float band = sin(vD * 22.0 + uTime * 0.7) * 0.5 + 0.5;",
  "  vec3 col = mix(core, mid, band);",
  "  col = mix(col, ice, fres * 0.85);",
  "  float spec = pow(max(dot(reflect(-v, n), normalize(vec3(0.35, 0.75, 0.6))), 0.0), 30.0);",
  "  col += hot * spec * 0.65;",
  "  gl_FragColor = vec4(col, 1.0);",
  "}",
].join("\n");

export const BOW_VERT = [
  "uniform float uVelocity; varying vec2 vUv;",
  "void main(){",
  "  vUv = uv;",
  "  vec3 p = position;",
  "  float arch = cos((uv.x - 0.5) * 3.14159265);",
  "  p.y += arch * uVelocity;",
  "  gl_Position = projectionMatrix * modelViewMatrix * vec4(p, 1.0);",
  "}",
].join("\n");

export const BOW_FRAG = [
  "precision highp float;",
  "uniform sampler2D uTex; uniform vec2 uSize; uniform vec2 uImg; uniform float uRadius; uniform float uAlpha;",
  "varying vec2 vUv;",
  "float sdRound(vec2 p, vec2 b, float r){ vec2 q = abs(p) - b + r; return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r; }",
  "void main(){",
  "  float ar = uSize.x / max(uSize.y, 1.0);",
  "  float ia = uImg.x / max(uImg.y, 1.0);",
  "  vec2 uv = vUv;",
  "  if (ar > ia) { uv.y = (uv.y - 0.5) * (ia / ar) + 0.5; }",
  "  else { uv.x = (uv.x - 0.5) * (ar / ia) + 0.5; }",
  "  vec4 tex = texture2D(uTex, uv);",
  "  vec2 p = (vUv - 0.5) * uSize;",
  "  float d = sdRound(p, uSize * 0.5, uRadius);",
  "  float a = 1.0 - smoothstep(0.0, 1.5, d);",
  "  gl_FragColor = vec4(tex.rgb, tex.a * a * uAlpha);",
  "}",
].join("\n");
